version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: dearwith
    volumes:
      - mongo-data:/data/db

  app:
    image: ${CI_REGISTRY_IMAGE}:${TAG}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/dearwith?authSource=admin
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo-data: